name: Cached Checking

on:
  workflow_dispatch:

jobs:
  run-tests-and-send-report:
    name: Run Tests and Send Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      # Kiểm tra xem cache có được khôi phục thành công không
      - name: Check if Maven cache was restored
        run: |
          if [ "${{ steps.maven-cache.outputs.cache-hit }}" = "true" ]; then
            echo "Maven cache restored successfully."
          else
            echo "Maven cache not found. Dependencies will be downloaded from scratch."
          fi

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :1 -screen 0 1920x1080x24 &

      - name: Set DISPLAY variable
        run: export DISPLAY=:1

      - name: Run Maven Tests
        env:
          DISPLAY: :1 # IMPORTANT: Set the DISPLAY environment variable
        run: mvn clean test