name: Run Tests and Send Allure Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  run-tests-and-send-report:
    name: Run Tests and Send Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :1 -screen 0 1920x1080x24 &

      - name: Set DISPLAY variable
        run: export DISPLAY=:1

      - name: Run Maven Tests
        env:
          DISPLAY: :1 # Quan trọng: Truyền biến DISPLAY vào quá trình chạy Maven
        run: mvn clean test

      - name: Get Current Date and Time
        if: always()
        id: date
        run: echo "timestamp=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./target/allure-results -c -o report/allure-report_${timestamp}
          zip -r report/allure-report_${timestamp}.zip allure-zip/allure-report_${timestamp}

      - name: Send Email with Test Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          to: lqthai07t3@gmail.com
          from: thai07t3@gmail.com
          smtp-server: smtp.gmail.com
          smtp-port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "(${{ env.timestamp }}) - Test Report - Allure"
          body: |
            <h2>Test Report</h2>
            <p>Chào bạn,</p>
            <p>Đây là báo cáo kiểm thử tự động từ GitHub Actions.</p>
#            <p>Thời gian kiểm thử: <strong>${{ env.timestamp }}</strong></p>
#            <p>Vui lòng xem báo cáo đính kèm.</p>
          content_type: text/html
#          attachments: report/allure-report_${{ env.timestamp }}.zip