name: Run Tests and Send Allure Report

on:
  workflow_dispatch: # Cho phép chạy thủ công
  schedule:
    # Chạy vào 9h sáng hàng ngày (giờ UTC)
    - cron: "0 9 * * *"

jobs:
  run-tests-and-send-report:
    name: Run Tests and Send Report
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập môi trường JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Bước 3: Chạy kiểm thử với Maven
      - name: Run Maven Tests
        run: mvn clean test allure:report

      - name: Get Current Date and Time
        id: date
        run: echo "timestamp=$(date +"%Y-%m-%d_%H-%M-%S")" >> $GITHUB_ENV # Lấy ngày giờ

      # Bước 4: Tạo file ZIP cho báo cáo Allure
      - name: Archive Allure Report
        run: |
          mkdir -p report
          zip -r "report/allure-report_${{ env.timestamp }}.zip" target/site/allure-maven-plugin

      # Bước 5: Gửi báo cáo qua email
      - name: Send Email with Test Report
        uses: dawidd6/action-send-mail@v3
        with:
          to: lqthai07t3@gmail.com # Email nhận
          from: thai07t3@gmail.com # Email gửi
          smtp-server: smtp.gmail.com
          smtp-port: 587
          username: ${{ secrets.SMTP_USERNAME }} # Đã thêm vào GitHub Secrets
          password: ${{ secrets.SMTP_PASSWORD }} # Đã thêm vào GitHub Secrets
          subject: "(${{ env.timestamp }}) - Test Report - Allure"
          body: |
            <h2>Test Report</h2>
            <p>Chào bạn,</p>
            <p>Đây là báo cáo kiểm thử tự động từ GitHub Actions.</p>
            <p>Thời gian kiểm thử: <strong>${{ env.timestamp }}</strong></p>
            <p>Vui lòng xem báo cáo đính kèm.</p>
          content-type: text/html
          attachments: report/allure-report.zip
